### ISSUE TITLE
Log messages do not contain full package name

### ISSUE THREAD

**Issue by greg-milette-bose** [MFlisar/Lumberjack#10]
Is it possible to make the log output contain the full package name instead of just the class name?

It could be as simple as disabling this:
```
    private fun getSimpleClassName(className: String): String {
        return className.substring(className.lastIndexOf('.') + 1)
    }

```

**Comment by MFlisar** [comment]
I added following in v5.2.1

https://github.com/MFlisar/Lumberjack/blob/72677e872186bdb470b8b9b8488d531ebbc705be/library/src/main/java/com/michaelflisar/lumberjack/L.kt#L45-L47

Feel free to replace it like following to get what you want (or adjust it to your likings):

    L.classNameFormatter = { it }
