### ISSUE TITLE
How to extend the provided Trees in Kotlin?

### ISSUE THREAD

**Issue by mohit92** [MFlisar/Lumberjack#12]
I want to extend the FileLoggingTree to add a default tag to all the logs but since the class is not open, I can not extend it.

**Comment by MFlisar** [comment]
Try v5.2.4

It allows you to provide a custom formatter like following:

    L.formatter = DefaultFormatter()

You can extend the [DefaultFormatter](https://github.com/MFlisar/Lumberjack/blob/66aa8824c6c9a2f1b0fd89eb8a64003b02cf9bba/library/src/main/java/com/michaelflisar/lumberjack/core/DefaultFormatter.kt) and add a prefix to any log line now.

Following would do what you want:

    class MyFormatter: DefaultFormatter()
    {
         override fun formatLogPrefix(lumberjackTag: String?, stackData: StackData) : String {
              return "MY-PREFIX-" + super.formatLogPrefix(lumberjackTag, stackData)
         }
    }
