### ISSUE TITLE
Getting parse error when using file logging. 

### ISSUE THREAD

**Issue by RahulMSASEENDRAN** [MFlisar/Lumberjack#15]
I am using file logging library and everything is working good in debug build but when it comes to release build I am getting parse error for date and tag in console.

expected: Date [ClassName:LineNumber method]: Log
What I am getting is: %PARSER_ERROR[d]	[p92:1 z]: log

**Comment by MFlisar** [comment]
If you are able to reproduce this issue inside the demo app, I could look into it. So I've no idea. Maybe the newest version does help, although I don't think so.

I'll close that for now.
