### ISSUE TITLE
Could not find com.github.MFlisar:CacheFileProvider:0.2.

### ISSUE THREAD

**Issue by saptarshifm** [MFlisar/Lumberjack#17]
We were using Lumberjack in our android project since a long time. Recently, in one of our builds, we came across the following error : 
> Could not resolve all files for configuration ':fairmatic:debugRuntimeClasspath'.
   > Could not find com.github.MFlisar:CacheFileProvider:0.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/MFlisar/CacheFileProvider/0.2/CacheFileProvider-0.2.pom
       - file:/home/runner/.m2/repository/com/github/MFlisar/CacheFileProvider/0.2/CacheFileProvider-0.2.pom
       - https://jcenter.bintray.com/com/github/MFlisar/CacheFileProvider/0.2/CacheFileProvider-0.2.pom
       - https://jitpack.io/com/github/MFlisar/CacheFileProvider/0.2/CacheFileProvider-0.2.pom
       - https://s01.oss.sonatype.org/content/repositories/snapshots/com/github/MFlisar/CacheFileProvider/0.2/CacheFileProvider-0.2.pom
     Required by:
         project :fairmatic > com.github.MFlisar.Lumberjack:lumberjack-feedback:5.2.6 > com.github.MFlisar:FeedbackManager:2.0.3

Please advise on what should be done.
Thanks
PS: We are using Lumberjack 5.2.6 in our project.

**Comment by MFlisar** [comment]
Check out following please:
https://github.com/jitpack/jitpack.io/issues/5973

Sadly, I have no control over jitpack and can't fix that...

Which modules of lumberjack do you use? You can at least remove the viewer/feedback module, the core does not have any dependency on my feedback library. And then you can add the newest feedback library and use it directly to just get the function to send a log file. If you need the viewer you should upgrade though...

Alternatively download the correct tags of lumberjack and my feedback manager  and build it locally or inside a fork on github yourself...

Alternative 3 is to download the tag 0.2 and build a jar locally and add it to your project and exclude the transitive dependency from lumberjack

**Comment by MFlisar** [comment]
I made a new branch of my cache file provider library based on the old 0.2 tag and adjusted it to build with the newest gradle version. You can try something like following to keep using the old version of lumberjack:

```kotlin
// adjust your lumberjack dependencies and remove the cache file provider dependency from it
implementation("com.michaelflisar.lumberjack:...") {
	exclude(group = "com.github.MFlisar", module = "CacheFileProvider")
}
// add following cache file provider manually instead (its the new build of the adjusted 0.2 version)
implementation("com.github.MFlisar:CacheFileProvider:15c65e2b2d")
```

Please let me know if that helps.

**Comment by saptarshifm** [comment]
@MFlisar We tried the above and still came accross this error:
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/michaelflisar/cachefileprovider/CacheFileProviderUtil;
                                                                                                    	at com.michaelflisar.feedbackmanager.internal.FeedbackUtil.copyFileToCache(FeedbackUtil.kt:15)
                                                                                                    	at com.michaelflisar.feedbackmanager.Feedback.buildIntent(Feedback.kt:36)
                                                                                                    	at com.michaelflisar.feedbackmanager.Feedback.startEmailChooser(Feedback.kt:57)
                                                                                                    	at com.michaelflisar.lumberjack.ExtensionFeedbackKt.sendFeedback(ExtensionFeedback.kt:30)
                                                                                                    	at com.michaelflisar.lumberjack.ExtensionFeedbackKt.sendFeedback$default(ExtensionFeedback.kt:15)

**Comment by MFlisar** [comment]
I close this, as i can't help here and as this is a jitpack issue that I can't influence. Updating is the best option or dowloading and building everything locally alternatively...
