### ISSUE TITLE
Create different instance or store to a different file

### ISSUE THREAD

**Issue by AlexandruDev** [MFlisar/Lumberjack#19]
Hello! First of all, thank you for this awesome library, it really helped me developing my VOIP app.

Currently I setup the library in the Application class, and use it throughout the app to store all logs in the log file.

`@HiltAndroidApp
class MyApp : Application() {

    override fun onCreate() {
        super.onCreate()
        initLumberjackLogger()
    }

    private fun initLumberjackLogger() {
        // Install the implementation
        L.init(LumberjackLogger)
        L.enable(BuildConfig.DEBUG)

        // Install loggers
        val setup = FileLoggerSetup.Daily(this, fileExtension = FILE_LOGGER_EXTENSION).also {
            FILE_LOGGING_SETUP = it
        }
        L.plant(FileLogger(setup))
    }
    
     companion object {
        const val FILE_LOGGER_EXTENSION = "txt"
        lateinit var FILE_LOGGING_SETUP: IFileLoggingSetup
       lateinit var FILE_LOGGING_SETUP_TEST: IFileLoggingSetup
    }
`

What I want to achieve is when I open the CallingActivity class, to store all logs from that activity in the "main" log file  but also in a **separate file** called: **call1_2024_03_12.txt** for example. I tried to create a new **FileLoggerSetup**, but from here I  don't know how to make all logs to be stored in a different file.

`@AndroidEntryPoint
class CallingActivity : ProximitySensorActivity() {

    private lateinit var binding: ActivityCallingBinding
    private val viewModel by viewModels<CallingViewModel>()

     override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        initBinding()
        initLumberjackLogger()
    }

    private fun initLumberjackLogger() {
        val setup = FileLoggerSetup.Daily(
            context = this,
            fileExtension = MyApp.FILE_LOGGER_EXTENSION,
            fileBaseName = getDynamicCallIdentifier() // returns a dynamic name for each call
        ).also {
                MyApp.FILE_LOGGING_SETUP_TEST = it
        }
        L.plant(FileLogger(setup))
    }
`

Can someone give me some suggestions on how I can achieve this?
Thank you!

**Comment by MFlisar** [comment]
I just made an update and extracted some logic of the daily setup into a base class that can be reused by new setups.

Check out the current existing implemtations:

https://github.com/MFlisar/Lumberjack/blob/49ee875794af26f296931d632c79a2d276ef2793/library/loggers/lumberjack/file/src/main/java/com/michaelflisar/lumberjack/loggers/file/FileLoggerSetup.kt#L57-L61
https://github.com/MFlisar/Lumberjack/blob/49ee875794af26f296931d632c79a2d276ef2793/library/loggers/lumberjack/file/src/main/java/com/michaelflisar/lumberjack/loggers/file/FileLoggerSetup.kt#L109-L124

**Suggestion**

I do pass in `FileLogger.Event.Data` to the `getFileKey` function now, this allows you to decide which file name is the correct one based on this data, it should contain everything you need to make your decision. The base setup will create log files based on the file key like following:
https://github.com/MFlisar/Lumberjack/blob/49ee875794af26f296931d632c79a2d276ef2793/library/loggers/lumberjack/file/src/main/java/com/michaelflisar/lumberjack/loggers/file/BaseFileLoggerSetup.kt#L25

I would do following:

* create your own setup implementation
* derive a key from the class name
* be aware, that the logging implemention in the background will close/open log files whenever the key changes - everthing is done on a backgroud thread, still keep that in mind

I don't know why you really need files for each class, maybe think about using multiple instances of FileLoggers and add some filter to them 'FileLogger(setup, filter = ...)`?

**Comment by AlexandruDev** [comment]
Thank you @MFlisar, I managed to create a different log file for the activity responsible with the incoming/outgoing calls and a separate one for the entire app.

I'l close this.
