### ISSUE TITLE
Overlay logger - Open advanced activity

### ISSUE THREAD

**Issue by MFlisar** [MFlisar/Lumberjack#4]
Add a button to launch an activity that shows the logs and offers advanced filter options like:
* filter
* search
* sort?

**Comment by Isanderthul** [comment]
This will be awesome, it would be great if there was an export option to send the txt file via email. So my testers can just email me the logs.

**Comment by MFlisar** [comment]
You can always use the file logger and send the created files via mail...

Currently I have no need for the activity, so if nobody else adds it (it shouldn't be that much work) it won't come that fast. I just wanted to write down the idea...

**Comment by MFlisar** [comment]
added with the new viewer module
