### ISSUE TITLE
code line number is repeated

### ISSUE THREAD

**Issue by greg-milette-bose** [MFlisar/Lumberjack#9]
The logging output contains the Line number twice. It would be better if it were included once and also if it were clickable still.

Examples:

Existing log:
`07-01 10:07:12.446 30867 30867 D [<MyTag@> LogExperiment:24 log]: My test log (LogExperiment.kt:24)`

Desired log:
`07-01 10:07:12.446 30867 30867 D [<MyTag@> LogExperiment:24 log]: My test log`

here is some example code:
```
    private fun log() {
        log2()
    }

    private fun log2() {
        d { "test log2 "}
        log3()
    }

    private fun log3() {
        d { "test log3 "}
    }
```

```
/TestActivity:50 log3]: test log3  (TestActivity.kt:50)
```

there is no need to include `TestActivity` twice it could be just:
```
/TestActivity:50 log3]: test log3 
```

**Comment by MFlisar** [comment]
That's desired, use following to disable this when setting up lumberjack:

    L.plant(ConsoleTree(appendClickableLink = false))

The variable name should explain why there is a need to append this
